version: "3"
services:
    web:
      image: docker push jackdhub/jdk-mvn-addressbook:php
      ports:
      - "8001-8002:80"
      deploy:
          replicas: 2
      depends_on:
      - mysql
    mysql:
      image: docker push jackdhub/jdk-mvn-addressbook:mysql
      volumes:
      - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
volumes:
   db_data: {}

